#include <iostream>
#include <sys/socket.h>
#include <netinet/in.h>
#include <filesystem>
#include <sstream>
#include <fstream>
#include <thread>
#include <signal.h>
#include <unistd.h>
#include <cstring>
#include <vector>
#include <ldap.h>